name: Run terraform fmt
on:
  pull_request:

jobs:
  terraform:
    name: terraform fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check -recursive
