name: Run terraform fmt
on:
  pull_request:

permissions: read-all

jobs:
  terraform:
    name: terraform fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive
